export const config = {
  GALLERY_MNEMONIC: process.env.REACT_APP_GALLERY_MNEMONIC, // DO NOT EXPOSE!

  GALLERY_PUBLIC:
    process.env.GALLERY_PUBLIC || process.env.REACT_APP_NEXT_PUBLIC_GALLERY_PUBLIC,
    ALGO_URL: process.env.REACT_APP_ALGO_URL || process.env.REACT_APP_NEXT_PUBLIC_ALGO_URL,
    INDEXER_URL: process.env.REACT_APP_INDEXER_URL || process.env.REACT_APP_NEXT_PUBLIC_INDEXER_URL,
    EXPLORER_URL: process.env.REACT_APP_EXPLORERE_URL || process.env.REACT_APP_NEXT_PUBLIC_INDEXER_URL,
};
