export const config = {
  GALLERY_MNEMONIC: process.env.REACT_APP_GALLERY_MNEMONIC, // DO NOT EXPOSE!

  ALGO_TOKEN: process.env.REACT_APP_ALGO_TOKEN,

  GALLERY_PUBLIC:
    process.env.GALLERY_PUBLIC ||
    process.env.REACT_APP_NEXT_PUBLIC_GALLERY_PUBLIC,
  ALGO_URL:
    process.env.REACT_APP_ALGO_URL ||
    process.env.REACT_APP_NEXT_PUBLIC_ALGO_URL,
  INDEXER_URL:
    process.env.REACT_APP_INDEXER_URL ||
    process.env.REACT_APP_NEXT_PUBLIC_INDEXER_URL,
 
  PORT: process.env.REACT_APP_PORT,
  ALGO_NETWORK:  process.env.REACT_APP_ALGO_NETWORK
};

